# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bd41e811552f118ad9d47421f91389b44dce6cc3e691e9f50f50c46b231aa6e9b79a7c58d2d2b2851967aa7c141e6e1447cc6c272fa8e55d35316885388e0e7

test:
  secret_key_base: a0e14b2813b06de1b25eb7bdf9cc52bcfe6fba04b6a8919a8e97be7eff5e6fdda9d2daaf522c83b414c3ff6aa43b8bb320a4f8249428e124ed89ba8d2236e3d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
